app_reserva/urls.py
from django.urls import path
from .views import home, create_task, mapa, signin, signup, tasks, signout
from . import views


urlpatterns = [
    path('', home, name='home'),
    path('create_task/', create_task, name='create_task'),
    path('mapa/', mapa, name='mapa'),
    path('signin/', signin, name='signin'),
    path('signup/', signup, name='signup'),
    path('tasks/', tasks, name='tasks'),
    path('actualizar-tarea/', views.actualizar_tarea, name='actualizar_tarea'),
    path('eliminar_tarea/', views.eliminar_tarea, name='eliminar_tarea'),
    path('create_task/', views.create_task, name='create_task'),
    path('logout/', signout, name='logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_reserva.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_reserva/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

# Create your models here.


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rut = models.CharField(max_length=20, verbose_name="RUT")
    email = models.EmailField(verbose_name="Correo electrónico")
    descripcion = models.TextField(verbose_name="Descripción")
    evidencia = models.ImageField(upload_to='evidencias/', verbose_name="Evidencia (JPG)")
    latitud = models.DecimalField(max_digits=9, decimal_places=6, verbose_name="Latitud")
    longitud = models.DecimalField(max_digits=9, decimal_places=6, verbose_name="Longitud")
    fecha = models.DateField(default=now, verbose_name="Fecha")
    hora = models.TimeField(default=now, verbose_name="Hora")
    dias_transcurridos = models.IntegerField(default=0, verbose_name="Días transcurridos")
    estado = models.CharField(max_length=50,
        choices=[
            ('Pendiente', 'Pendiente'),
            ('En Proceso', 'En Proceso'),
            ('Completada', 'Completada'),
        ],
        default='Pendiente',
        verbose_name="Estado",
    )

    def __str__(self):
        return f"Task: {self.user} - {self.estado}"

app_reserva/forms.py
from django.forms import ModelForm
from .models import Task

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['rut', 'email', 'descripcion', 'evidencia', 'latitud', 'longitud', ]

app_reserva/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse
from .forms import TaskForm
from .models import Task
import folium
from folium.plugins import FastMarkerCluster
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages

# Create your views here.

# Vista home.
def home(request):
    return render(request, 'home.html')

@login_required
def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST, request.FILES)
        print("Datos del formulario:", form.data)

        if form.is_valid():
            # Acceder a cleaned_data solo después de que el formulario sea válido
            latitud = form.cleaned_data.get('latitud')
            longitud = form.cleaned_data.get('longitud')

            # Redondeamos latitud y longitud a 6 decimales
            if latitud:
                latitud = round(latitud, 6)
            if longitud:
                longitud = round(longitud, 6)

            # Asignar latitud y longitud redondeados a los datos del formulario
            task = form.save(commit=False)
            task.latitud = latitud
            task.longitud = longitud
            task.user = request.user
            task.save()

            return redirect('tasks')
        else:
            print("Errores del formulario:", form.errors)
            return render(request, 'create_task.html', {'form': form, 'error': 'Por favor, corrige los errores del formulario.'})

    else:
        form = TaskForm()
        return render(request, 'create_task.html', {'form': form})




def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {
            'form': UserCreationForm
        })
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                #Registro del usuario
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('tasks')
            except IntegrityError:
                return render(request, 'signup.html', {
                    'form': UserCreationForm,
                    "error": 'El usuario ya Existe'
                })
        return render(request, 'signup.html', {
                    'form': UserCreationForm,
                    'error': 'Las contraseñas no coinciden'})
    

@login_required
def tasks(request):
    tasks = Task.objects.all()
    return render(request, 'tasks.html', {'tasks': tasks})


def signout(request):
    logout(request)
    return redirect('home')


def signin(request):
    if request.method == 'GET':
        return render(request, 'signin.html', {
            'form': AuthenticationForm
        })
    else:
        user =authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'signin.html', {
                'form': AuthenticationForm,
                'error': 'Usuario o Contraceña incorrecta'
            })
        
        else:
            login(request, user)
            return redirect('tasks')
        

@login_required
def mapa(request):

    # Recupero todas las sucursales
    locations = Task.objects.all()

    # Defino el mapa
    initialMap = folium.Map(location=[-33.45694, -70.64827], zoom_start=11)

    for location in locations:
        coordinates = (location.latitud, location.longitud)
        folium.Marker(coordinates, popup='Usuario '+ location.user.username +'Descripción '+ location.descripcion +'Estado '+ location.estado).add_to(initialMap)


    context = {'map':initialMap._repr_html_(), 'locations': locations}
    return render(request, 'mapa.html', context)


# Actualizar Task
def obtener_tarea(request, id):
    tarea = Task.objects.get(id=id)
    data = {
        'id': tarea.id,
        'descripcion': tarea.descripcion,
        'estado': tarea.estado,
    }
    return JsonResponse(data)


def actualizar_tarea(request):
    if request.method == 'POST':
        try:
            task_id = request.POST.get('id')
            descripcion = request.POST.get('descripcion')
            estado = request.POST.get('estado')
            
            # Verifica que los datos necesarios están presentes
            if not task_id or not descripcion or not estado:
                raise ValueError("Faltan datos para actualizar la tarea.")

            # Obtener la tarea y actualizar los campos
            tarea = get_object_or_404(Task, id=task_id)
            tarea.descripcion = descripcion
            tarea.estado = estado
            tarea.save()
            
            # Agregar un mensaje de éxito (opcional)
            messages.success(request, "Tarea actualizada con éxito.")
        
        except Task.DoesNotExist:
            messages.error(request, "La tarea no existe.")
            return redirect(request.META.get('HTTP_REFERER', '/'))  # Redirige al origen
            
        except ValueError as e:
            messages.error(request, str(e))
            return redirect(request.META.get('HTTP_REFERER', '/'))  # Redirige al origen
        
        except Exception as e:
            # Captura cualquier otro error inesperado
            messages.error(request, f"Error al actualizar la tarea: {str(e)}")
            return redirect(request.META.get('HTTP_REFERER', '/'))  # Redirige al origen

        # Redirigir a la misma página desde donde se realizó la solicitud
        return redirect(request.META.get('HTTP_REFERER', '/'))

    else:
        return HttpResponse('Método no permitido', status=405)
    

#Eliminar Registro
def eliminar_tarea(request):
    if request.method == 'POST':
        task_id = request.POST['id']
        
        # Obtener la tarea y eliminarla
        tarea = get_object_or_404(Task, id=task_id)
        tarea.delete()
        
        # Redirigir a la misma página
        return redirect(request.META.get('HTTP_REFERER', '/'))  # Redirige a la misma página o al home
    else:
        return HttpResponse('Método no permitido', status=405)

app_reserva/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aplicacion Django</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <!-- CSS -->
    <style>
        .nav-link:hover {
            color: #ff6347; /* Cambia el color al pasar el ratón */
            text-decoration: underline; /* Subraya el enlace al hacer hover */
        }
    </style>
    
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">ALTURBAN</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">

                <li class="nav-item">
                    <a class="nav-link" href="/"><i class="bi bi-house-add me-2"></i>Home |</a>
                </li>
                
                {% if user.is_authenticated and user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="/admin"><i class="bi bi-person-fill-add me-2"></i>Admin |</a>
                </li>
                {% endif %}

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/tasks"><i class="bi bi-table me-2"></i>Tabla Registro |</a>
                </li>
                {% endif %}
                
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/create_task"><i class="bi bi-pencil-square me-2"></i>Reportar Peligro |</a>
                </li>
                {% endif %}

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/mapa"><i class="bi bi-globe-americas me-2"></i>Mapa |</a>
                </li>
                {% endif %}

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="btn btn-danger" href="/logout"><i class="bi bi-door-closed me-2"></i>Cerrar Sesión</a>
                </li>
    
                {% else %}
    
                <li class="nav-item">
                    <a class="nav-link" href="/signup"><i class="bi bi-person-fill-check me-2"></i>Registrase</a>
                </li>
                
                <li class="nav-item">

                    <a class="btn btn-warning" href="/signin"><i class="bi bi-door-open me-2"></i>Iniciar Sesión</a>
                </li>
                {% endif %}
                
            </ul>
          </div>
        </div>
      </nav>
    
    {% block content %}

        {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
        {% endif %}

    
    {% endblock %}
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

app_reserva/templates/create_task.html
{% extends 'base.html' %}


{% block content %}

<main class="container">
    <div class="row">
        <section class="col-md-4 offset-md-4 mt-5">

            <form action="/create_task/" method="POST" class="card card-body" enctype="multipart/form-data">
                <h1 class="text-center">Reportar</h1>
            
                {% if error %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endif %}
            
                {% csrf_token %}
                
                <div class="mb-3">
                    <label for="id_rut">RUT:</label>
                    <input type="text" name="rut" required id="id_rut" class="form-control" placeholder="Rut">
                </div>
            
                <div class="mb-3">
                    <label for="id_email">Email</label>
                    <input type="email" name="email" required id="id_email" class="form-control" placeholder="email">
                </div>
            
                <div class="mb-3">
                    <label for="id_descripcion">Descripcion</label>
                    <input type="text" name="descripcion" required id="id_descripcion" class="form-control" placeholder="Ingresa una descripcion">
                </div>
            
                <div class="mb-3">
                    <label for="id_evidencia">Evidencia (JPG)</label>
                    <input type="file" name="evidencia" accept="image/*" required id="id_evidencia" class="form-control">
                </div>
            
                <!-- Campos para latitud y longitud ocultos, que se llenan con los valores geolocalizados -->
                <input type="hidden" name="latitud" id="id_latitud_input">
                <input type="hidden" name="longitud" id="id_longitud_input">
            
                <div class="mb-3">
                    <label for="id_latitud">Latitud</label>
                    <span id="id_latitud" class="form-control">Cargando...</span> <!-- Mostrará la latitud -->
                </div>
                
                <div class="mb-3">
                    <label for="id_longitud">Longitud</label>
                    <span id="id_longitud" class="form-control">Cargando...</span> <!-- Mostrará la longitud -->
                </div>
                
                <button type="submit" class="btn btn-primary">Crear tarea</button>
            </form>
            
            <script>
                // Verificar si el navegador soporta geolocalización
                if (navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(function(position) {
                        // Obtener la latitud y longitud
                        var latitud = position.coords.latitude;
                        var longitud = position.coords.longitude;
            
                        // Redondear a 6 decimales
                        latitud = latitud.toFixed(6);
                        longitud = longitud.toFixed(6);
            
                        // Asignar los valores de latitud y longitud a las etiquetas
                        document.getElementById('id_latitud').innerText = latitud;
                        document.getElementById('id_longitud').innerText = longitud;
            
                        // Llenar los campos ocultos con los valores de latitud y longitud
                        document.getElementById('id_latitud_input').value = latitud;
                        document.getElementById('id_longitud_input').value = longitud;
                    }, function(error) {
                        console.log("Error al obtener la ubicación: " + error.message);
                        alert("No se pudo obtener la ubicación. Por favor, habilita la geolocalización.");
                    });
                } else {
                    console.log("Geolocalización no es compatible con este navegador.");
                    alert("Tu navegador no soporta geolocalización.");
                }
            </script>
            



        </section>

    </div>

</main>




{% endblock %}

app_reserva/templates/home.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<main>

    <section class="py-5 text-center container">

        <div class="row py-lg-5">

            <div class="col-lg-6 col-md-8 mx-auto">

                <h1 class="fw-light">ALTURBAN</h1>
                <p class="lead text-muted">Algo corto y principal sobre la colección a continuación: su contenido,
                    el creador, etc. Hágalo breve y agradable, pero no demasiado corto para que la gente no lo pase
                    por alto por completo.</p>

            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <!-- Primera imagen-->
                        <img src="{% static 'img/bache1.jpg' %}" alt="" width="100%" height="225">

                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                                <p></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm">
                        <!-- Segunda imagen-->
                        <img src="{% static 'img/bache2.jpg' %}" alt="" width="100%" height="225">
                        <div class="card-body">
                            <p></p>
                            <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm">
                        <!-- Tercera imagen-->
                        <img src="{% static 'img/cable 1.jpg' %}" alt="" width="100%" height="225">
                        <div class="card-body">
                            <p></p>
                            <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>
                    </div>
                </div>

            </div><br>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <!-- cuarta imagen-->
                        <img src="{% static 'img/cable-caido.jpg' %}" alt="" width="100%" height="225">

                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                                <p></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm">
                        <!-- quinta imagen-->
                        <img src="{% static 'img/cable-caido2.jpg' %}" alt="" width="100%" height="225">
                        <div class="card-body">
                            <p></p>
                            <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm">
                        <!-- sexta imagen-->
                        <img src="{% static 'img/cables2.jpg' %}" alt="" width="100%" height="225">
                        <div class="card-body">
                            <p></p>
                            <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</main>


{% endblock %}

app_reserva/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<main>

    <section class="py-5 text-center container">

        <div class="row py-lg-5">

            <div class="col-lg-6 col-md-8 mx-auto">

                <h1 class="fw-light">ALTURBAN</h1>
                <p class="lead text-muted">Algo corto y principal sobre la colección a continuación: su contenido,
                    el creador, etc. Hágalo breve y agradable, pero no demasiado corto para que la gente no lo pase
                    por alto por completo.</p>

            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <!-- Primera imagen-->
                        <img src="{% static 'img/bache1.jpg' %}" alt="" width="100%" height="225">

                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                                <p></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm">
                        <!-- Segunda imagen-->
                        <img src="{% static 'img/bache2.jpg' %}" alt="" width="100%" height="225">
                        <div class="card-body">
                            <p></p>
                            <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm">
                        <!-- Tercera imagen-->
                        <img src="{% static 'img/cable 1.jpg' %}" alt="" width="100%" height="225">
                        <div class="card-body">
                            <p></p>
                            <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>
                    </div>
                </div>

            </div><br>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <!-- cuarta imagen-->
                        <img src="{% static 'img/cable-caido.jpg' %}" alt="" width="100%" height="225">

                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                                <p></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm">
                        <!-- quinta imagen-->
                        <img src="{% static 'img/cable-caido2.jpg' %}" alt="" width="100%" height="225">
                        <div class="card-body">
                            <p></p>
                            <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm">
                        <!-- sexta imagen-->
                        <img src="{% static 'img/cables2.jpg' %}" alt="" width="100%" height="225">
                        <div class="card-body">
                            <p></p>
                            <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</main>


{% endblock %}

app_reserva/templates/mapa.html
{% extends 'base.html' %}


{% block content %}

{% load static %}

<!-- CSS de Leaflet (usado por Folium) -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.css" integrity="sha512-BtPld3NBZ9qZmlus9SE2AvO9fu0ClOgxmjKtxer52+JlZLp4dTL0PfZbWcBDwt5StKpFwhFsWFF92WInrQ5DAw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
<!-- JavaScript de Leaflet -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.js" integrity="sha512-vY3fak6DDAeG9Tq1KDgd8T24kVtHbNoqlENvH/aHDaYw2N7lP1hyQ52jW7KTTFdR5dPUFjWrMkK8k3IC0z74Nw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<div class="row mt-4">
    <div class="col-md-2">
        <h3>Mapa Zona de Riesgos</h3>
            <p class="lead">Top 10 Ubicaciones</p>

        <ol class="list-group list-group-numbered">
            {% for location in locations|slice:":10" %} <!--solo muestra un top 10-->
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">{{ location.user.username }}</div>
                    {{ location.descripcion }}
                </div>
            </li>
            {% endfor %}
        </ol>
    </div>

    <div class="col-md-9">
        {{ map|safe }}
    </div>
</div>


{% endblock %}

app_reserva/templates/signin.html
{% extends 'base.html' %}

{% block content %}

<main class="container">
    <div class="row">
        <section class="col-md-4 offset-md-4 mt-5" >

            <form action="/signin/" method="POST" class="card card-body">
        
                <h1 class="text-center">Iniciar Sesión</h1>
            
                {{error}}
            
                {% csrf_token %}
                
                <div class="mb-3">
                    <label for="username">Nombre</label>
                    <input type="text" name="username" id="username" class="form-control" 
                    placeholder="Nombre">
            
                </div>
            
                <div class="mb-3">
                    <label for="password">Contraseña</label>
                    <input type="password" name="password" id="password" class="form-control" 
                    placeholder="Contraseña">
            
                </div>
            
            
            
                <button class="btn btn-primary">
                    Enviar
                </button>
            
            
            </form>
        
        
        
        </section>

    </div>

</main>



{% endblock %}

app_reserva/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<main class="container">

<div class="row">
    <div class="col-md-4 offset-md-4 mt-5">
        <form action="/signup/" method="POST" class="card card-body">

            <h1 class="text-center">Registrase</h1>

            {{error}}
            {% csrf_token %}
        
            <div class="mb-3">
                <label for="username">Nombre</label>
                <input type="text" name="username" id="username" class="form-control" 
                placeholder="Nombre">

            </div>

            <div class="mb-3">
                <label for="password1">Contraseña</label>
                <input type="password" name="password1" id="password1" class="form-control" 
                placeholder="Contraseña">

            </div>

            <div class="mb-3">
                <label for="password2">Confirmar Contraseña</label>
                <input type="password" name="password2" id="password2" class="form-control" 
                placeholder="Confirmar Contraseña">

            </div>
        
        
            <button class="btn btn-primary">
                Enviar
            </button>
        
        </form>

    </div>

</div>

</main>

{% endblock %}